version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: dockerfiles/backend.dockerfile
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - chat_app_uploads:/app/uploads
      - ./:/app
      - /app/node_modules
    depends_on:
      - mongodb
      - redis
    
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - chat_app_mongodb_data:/data/db
    env_file:
      - .env
    
  redis:
    image: redis
    ports:
      - 6379:6379


volumes:
  chat_app_uploads:
  chat_app_mongodb_data:
